name: Windows C/C++ CI

on:
  push:
    branches: [ nimish ]
  pull_request:
    branches: [ nimish ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: gcc 3_Implementation/matrix_cal.c -o matrix_calculator.exe
    - name: Run
      run: .\matrix_calculator.exe
