name: C/C++ CI

on:
  push:
    branches: [ nimish ]
  pull_request:
    branches: [ nimish ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: gcc matrix_cal.c -o matrix.exe
    - name: Run
      run: ./matrix.exe
